export const muscles = [
    'Pecho',
    'Espalda',
    'Trapecios',
    'Hombros',
    'Bíceps',
    'Tríceps',
    'Cuádriceps',
    'Femoral',
    'Glúteos',
    'Abdomen',
    'Oblicuos',
    'Serrato',
    'Gemelos',
    'Sóleo',
    'Lumbares',
    'Romboides',
    'Bíceps femoral',
    'Trapecio bajo',
    'Psoas',
    'Aductores',
    'Abductores',
    'Flexores de cadera',
    'Extensores de muñeca',
    'Flexores de muñeca',
    'Flexores de codo',
    'Flexores de rodilla',
    'Extensores de rodilla',
    'Trapecio alto',
    'Brazo anterior',
    'Escalenos',
    'Flexores de tobillo',
    'Dorsales',
    'Glúteo mayor',
    'Glúteo medio',
    'Glúteo menor',
    'Espalda baja',
    'Flexores de cadera',
    'Oblicuos internos',
    'Oblicuos externos',
    'Cuello',
    'Antebrazos',
    'Muñeca'
]

export const equipment = [
    'Mancuernas',
    'Barras',
    'Pesas',
    'Discos de peso',
    'Máquinas de cardio (bicicleta estática, elíptica, etc.)',
    'Banco de pesas',
    'Banco inclinado',
    'Banco plano',
    'Máquina de press de banca',
    'Máquina de remo',
    'Cinta de correr',
    'Kettlebells',
    'Bandas elásticas',
    'Cuerda para saltar',
    'Máquina de extensiones de pierna',
    'Máquina de curl de pierna',
    'Máquina de glúteos',
    'Pull-up bar (barra para dominadas)',
    'TRX (sistema de suspensión)',
    'Barras paralelas',
    'Plataformas de saltos',
    'Rueda abdominal',
    'Colchonetas de yoga',
    'Balón medicinal',
    'Balón suizo',
    'Cinturón de pesas',
    'Ganchos para levantamiento de pesas',
    'Mangas de compresión',
    'Guantes de gimnasio',
    'Zapatillas deportivas de entrenamiento',
    'Cinturón lumbar',
    'Pesas rusas',
    'Máquina de cardio (remadora)',
    'Escalera de agilidad',
    'Plataforma de step',
    'Pelotas de estabilidad',
    'Máquinas de abdominales',
    'Pesas de tobillo',
    'Cajas pliométricas',
    'Ruedas para abdominales',
    'Cinturón de levantamiento de pesas',
    'Soga de batalla',
    'Mancuernas ajustables',
    'Rodillos de foam (foam roller)'
  ]